# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Veranika Isakova"
resume_title:                   "Junior Web Developer"
resume_contact_email:           "veranika.isakova89@gmail.com"
resume_contact_telephone:       "+31 6 14517801"
resume_contact_address:         "Sonmansstraat 5B, 3039DG Rotterdam"
resume_header_contact_info: "Sonmansstraat 5B, Rotterdam | +31614517801 | veranika.isakova89@gmail.com"
resume_header_intro: "<p>Recent graduate of a full-stack web development course, currently seeking opportunities for a role of a Junior Web Developer. Experienced in Ruby (Ruby on Rails), Javascript (React, Redux, Express) and excited to begin full-stack development.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/veranika-isakova"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/veronika.isakova"
  resume_linkedin_url:          "https://www.linkedin.com/in/veranika-isakova"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
